src/main/java/org/example/fitpass/common/ResponseMessage.java, src/main/java/org/example/fitpass/domain/gym/repository/GymRepository.java, src/main/java/org/example/fitpass/domain/reservation/controller/ReservationController.java, src/main/java/org/example/fitpass/domain/reservation/dto/ReservationRequestDto.java, src/main/java/org/example/fitpass/domain/reservation/dto/ReservationResponseDto.java, src/main/java/org/example/fitpass/domain/reservation/entity/Reservation.java, src/main/java/org/example/fitpass/domain/reservation/repository/ReservationRepository.java, src/main/java/org/example/fitpass/domain/reservation/service/ReservationService.java, src/main/java/org/example/fitpass/domain/trainer/repository/TrainerRepository.java, src/main/java/org/example/fitpass/domain/user/repository/UserRepository.java
- ex) Feature/reservation2 -> dev
- 예약 생성 기능 구현, 예약 가능시간 기능구현
- 관련 이슈 번호: #4 
=> [#4] Feature/reservation2

src/main/java/org/example/fitpass/common/Image.java, src/main/java/org/example/fitpass/domain/gym/entity/Gym.java
-  feature/add-column -> dev
- 이미지 엔티티 추가
- 관련 이슈 번호: #6 
- x
=> [#6] feat: image 엔티티 추가

src/main/java/org/example/fitpass/domain/post/controller/PostController.java, src/main/java/org/example/fitpass/domain/post/dto/request/PostCreateRequestDto.java, src/main/java/org/example/fitpass/domain/post/dto/request/PostUpdateRequestDto.java, src/main/java/org/example/fitpass/domain/post/dto/response/PostResponseDto.java, src/main/java/org/example/fitpass/domain/post/entity/Post.java, src/main/java/org/example/fitpass/domain/post/enums/PostStatus.java, src/main/java/org/example/fitpass/domain/post/enums/PostType.java, src/main/java/org/example/fitpass/domain/post/repository/PostRepository.java, src/main/java/org/example/fitpass/domain/post/service/PostService.java
- ex) post -> dev
- 단순 post CRUD
- 관련 이슈 번호: close #14 
=> feat : post CRUD

src/main/java/org/example/fitpass/domain/point/controller/PointController.java, src/main/java/org/example/fitpass/domain/point/dto/request/PointUseRefundRequestDto.java, src/main/java/org/example/fitpass/domain/reservation/controller/ReservationController.java, src/main/java/org/example/fitpass/domain/reservation/service/ReservationService.java
- ex) feature/Reservation3 -> dev
- 포인트와 연결, 예약 생성시 포인트 차감, 예약 취소 시 포인트 환불
- 관련 이슈 번호:  close #18 
- 예약, 포인트 CRUD MVP기능 구현 완료
=> [#18] 포인트와 연결, 예약 생성시 포인트 차감, 예약 취소 시 포인트 환불

src/main/java/org/example/fitpass/common/Image.java, src/main/java/org/example/fitpass/domain/gym/controller/GymController.java, src/main/java/org/example/fitpass/domain/gym/dto/request/GymRequestDto.java, src/main/java/org/example/fitpass/domain/gym/repository/GymRepository.java, src/main/java/org/example/fitpass/domain/gym/service/GymService.java, src/main/java/org/example/fitpass/domain/post/dto/request/PostUpdateRequestDto.java, src/main/java/org/example/fitpass/domain/post/dto/response/PostResponseDto.java, src/main/java/org/example/fitpass/domain/reservation/dto/request/ReservationRequestDto.java, src/main/java/org/example/fitpass/domain/reservation/dto/response/GetReservationResponseDto.java, src/main/java/org/example/fitpass/domain/reservation/dto/response/ReservationResponseDto.java, src/main/java/org/example/fitpass/domain/reservation/dto/response/TrainerReservationResponseDto.java, src/main/java/org/example/fitpass/domain/reservation/dto/response/UpdateReservationResponseDto.java, src/main/java/org/example/fitpass/domain/reservation/dto/response/UserReservationResponseDto.java, src/main/java/org/example/fitpass/domain/trainer/dto/TrainerReqeustDto.java, src/main/java/org/example/fitpass/domain/trainer/dto/TrainerResponseDto.java, src/main/java/org/example/fitpass/domain/trainer/entity/Trainer.java
- ex) feature/post -> dev
- 전체코드 리펙토링
- 관련 이슈 번호:  close #22 
=> fix : 코드리펙토링 issues#22

src/main/java/org/example/fitpass/common/error/ExceptionCode.java, src/main/java/org/example/fitpass/common/error/GlobalExceptionHandler.java
- ex) feature/post -> dev
- 단순 코드 수정
- 관련 이슈 번호: close #24 
=> [#24] fix : 에러 코드 수정

src/main/java/org/example/fitpass/common/error/ExceptionCode.java, src/main/java/org/example/fitpass/common/error/SuccessCode.java, src/main/java/org/example/fitpass/common/response/ResponseMessage.java, src/main/java/org/example/fitpass/domain/point/controller/PointController.java, src/main/java/org/example/fitpass/domain/point/dto/request/PointRequestDto.java, src/main/java/org/example/fitpass/domain/point/dto/response/PointResponseDto.java, src/main/java/org/example/fitpass/domain/point/service/PointService.java, src/main/java/org/example/fitpass/domain/reservation/controller/ReservationController.java, src/main/java/org/example/fitpass/domain/reservation/dto/request/ReservationRequestDto.java, src/main/java/org/example/fitpass/domain/reservation/service/ReservationService.java
- ex) feature/Point2 -> dev
- 예외처리 및 성공 응답처리 공통처리
- 관련 이슈 번호:  close #27 
- 예외처리 및 성공 응답처리 공통처리
=> [#27] feat : 예외처리 예외코드로 수정, ResponseMessage도 SuccessCode로 수정 완료

src/main/java/org/example/fitpass/common/error/ExceptionCode.java, src/main/java/org/example/fitpass/common/error/SuccessCode.java, src/main/java/org/example/fitpass/common/response/ResponseMessage.java, src/main/java/org/example/fitpass/domain/gym/controller/GymController.java, src/main/java/org/example/fitpass/domain/gym/entity/Gym.java, src/main/java/org/example/fitpass/domain/gym/repository/GymRepository.java, src/main/java/org/example/fitpass/domain/gym/service/GymService.java
- refactor/gym-exception-> dev
- 팀원들과의 응답처리 부분을 통일하기 위하여 형식에 맞게 리펙토링
- 관련 이슈 번호: close #29 
- x
=> [#29]Refactor/gym exception

src/main/java/org/example/fitpass/common/error/SuccessCode.java, src/main/java/org/example/fitpass/common/response/ResponseMessage.java, src/main/java/org/example/fitpass/domain/post/controller/PostController.java, src/main/java/org/example/fitpass/domain/post/dto/request/PostCreateRequestDto.java, src/main/java/org/example/fitpass/domain/post/dto/request/PostUpdateRequestDto.java, src/main/java/org/example/fitpass/domain/post/dto/response/PostResponseDto.java, src/main/java/org/example/fitpass/domain/post/entity/Post.java, src/main/java/org/example/fitpass/domain/post/enums/PostStatus.java, src/main/java/org/example/fitpass/domain/post/enums/PostType.java, src/main/java/org/example/fitpass/domain/post/repository/PostRepository.java, src/main/java/org/example/fitpass/domain/post/service/PostService.java
- ex) feature/post -> dev
- 코드 리펙토링 및 정리
- 페이징 생성
- 관련 이슈 번호: close #31 
=> fix : 코드 리펙토링 및 페이징 설정

build.gradle, src/main/java/org/example/fitpass/common/error/ExceptionCode.java, src/main/java/org/example/fitpass/config/RedissonConfig.java, src/main/java/org/example/fitpass/domain/reservation/service/ReservationService.java, src/test/java/org/example/fitpass/ReservationConcurrencyTest.java, src/test/resources/application-test.properties
- ex) feature/Reservation4 -> dev
- 예약 생성 동시성제어 DB 제약조건 + Redis를 이용한 분산 락 적용
- 관련 이슈 번호: close #45 
=> [#45] feat : 예약 생성 동시성제어 DB 제약조건 + Redis를 이용한 분산 락 적용

src/main/java/org/example/fitpass/common/error/SuccessCode.java, src/main/java/org/example/fitpass/domain/post/controller/PostController.java, src/main/java/org/example/fitpass/domain/post/enums/PostStatus.java, src/main/java/org/example/fitpass/domain/post/enums/PostType.java, src/main/java/org/example/fitpass/domain/post/repository/PostRepository.java, src/main/java/org/example/fitpass/domain/post/service/PostService.java
- ex) feature/post -> dev
- 게시물 GENERAL, NOTICE 분리
- 관련 이슈 번호: close #47
=> [#47] fix : 게시물 GENERAL, NOTICE 분리

src/main/java/org/example/fitpass/common/error/ExceptionCode.java, src/main/java/org/example/fitpass/domain/point/controller/AdminPointController.java, src/main/java/org/example/fitpass/domain/point/controller/PointController.java, src/main/java/org/example/fitpass/domain/reservation/dto/request/ReservationRequestDto.java, src/main/java/org/example/fitpass/domain/reservation/dto/request/UpdateReservationRequestDto.java, src/main/java/org/example/fitpass/domain/reservation/service/ReservationService.java
- ex) feature/Reservation5 -> dev
- 예약 권한 로직 추가 및 시간 및 날짜 NotNull로 수정
- 관련 이슈 번호: close #53 
=> [#53] feat : 예약 권한 로직 추가 및 시간 및 날짜 NotNull로 수정

src/main/java/org/example/fitpass/common/error/ExceptionCode.java, src/main/java/org/example/fitpass/common/error/SuccessCode.java, src/main/java/org/example/fitpass/domain/auth/controller/AuthController.java, src/main/java/org/example/fitpass/domain/user/controller/UserController.java, src/main/java/org/example/fitpass/domain/user/dto/LoginRequestDto.java, src/main/java/org/example/fitpass/domain/user/dto/UpdatePasswordRequestDto.java, src/main/java/org/example/fitpass/domain/user/dto/UpdatePhoneRequestDto.java, src/main/java/org/example/fitpass/domain/user/entity/User.java, src/main/java/org/example/fitpass/domain/user/repository/UserRepository.java, src/main/java/org/example/fitpass/domain/user/service/UserService.java
- ex) feat/signup -> dev
- 로그인 할 때 이메일, 비밀번호만 입력해도 로그인 가능
- 관련 이슈 번호: close #51 
=> Refactor : 로그인 Request 수정

src/main/java/org/example/fitpass/config/RedisCacheConfig.java
- ex) feat/post -> dev
- 어떤 작업을 했는지 간단히 설명
- 관련 이슈 번호:  close #65 
=> [#65] fix : RedisCacheConfig 등록

src/main/java/org/example/fitpass/common/error/ExceptionCode.java, src/main/java/org/example/fitpass/common/jwt/JwtAuthenticationFilter.java, src/main/java/org/example/fitpass/common/jwt/JwtTokenProvider.java, src/main/java/org/example/fitpass/common/jwt/RefreshTokenRequestDto.java, src/main/java/org/example/fitpass/common/redis/RedisConfig.java, src/main/java/org/example/fitpass/common/redis/RedisService.java, src/main/java/org/example/fitpass/common/security/CustomUserDetailsService.java, src/main/java/org/example/fitpass/domain/auth/controller/AuthController.java, src/main/java/org/example/fitpass/domain/auth/dto/response/SigninResponseDto.java, src/main/java/org/example/fitpass/domain/user/dto/LogoutRequestDto.java, src/main/java/org/example/fitpass/domain/user/service/UserService.java
- ex) feat/signup -> dev
- RefreshToken, AccessToken 나누고, redis 설정
- 관련 이슈 번호: close #61 
=> Refactor : redis 설정, 토큰 재설정

src/main/java/org/example/fitpass/domain/post/controller/PostController.java, src/main/java/org/example/fitpass/domain/post/dto/request/PostCreateRequestDto.java, src/main/java/org/example/fitpass/domain/post/dto/request/PostUpdateRequestDto.java, src/main/java/org/example/fitpass/domain/post/dto/response/PostResponseDto.java
- ex) feat/post -> dev
- 어떤 작업을 했는지 간단히 설명
- 관련 이슈 번호: close #71 
=> [#71] fix : 코드 리펙토링

src/main/java/org/example/fitpass/domain/auth/controller/AuthController.java, src/main/java/org/example/fitpass/domain/user/dto/UserRequestDto.java, src/main/java/org/example/fitpass/domain/user/service/UserService.java
- ex) feat/signup -> dev
- 이미지 처리 방법 변경
- 관련 이슈 번호: close #81 
=> Refactor : 이미지 부분 수정

src/main/java/org/example/fitpass/common/BaseEntity.java, src/main/java/org/example/fitpass/common/error/ExceptionCode.java, src/main/java/org/example/fitpass/common/error/SuccessCode.java, src/main/java/org/example/fitpass/domain/review/controller/ReviewController.java, src/main/java/org/example/fitpass/domain/review/controller/ReviewGetController.java, src/main/java/org/example/fitpass/domain/review/dto/request/ReviewCreateRequestDto.java, src/main/java/org/example/fitpass/domain/review/dto/request/ReviewUpdateRequestDto.java, src/main/java/org/example/fitpass/domain/review/dto/response/GymRatingResponseDto.java, src/main/java/org/example/fitpass/domain/review/dto/response/ReviewDetailResponseDto.java, src/main/java/org/example/fitpass/domain/review/dto/response/ReviewResponseDto.java, src/main/java/org/example/fitpass/domain/review/dto/response/TrainerRatingResponseDto.java, src/main/java/org/example/fitpass/domain/review/entity/Review.java, src/main/java/org/example/fitpass/domain/review/repository/ReviewRepository.java, src/main/java/org/example/fitpass/domain/review/service/ReviewService.java
- ex) feature/Review -> dev
- reivew CRUD 생성
- 관련 이슈 번호:close #83 
=> [#83] feat : reivew CRUD 생성

src/main/java/org/example/fitpass/domain/fitnessGoal/entity/DailyRecord.java, src/main/java/org/example/fitpass/domain/fitnessGoal/service/DailyRecordService.java
- ex) feature/FitnessGoal, Reservaition -> dev
- 어S3 연결 로직 수정
- 관련 이슈 번호: close #85 
=> feat : S3 연결 로직 수정

src/main/java/org/example/fitpass/common/Image/controller/ImageController.java, src/main/java/org/example/fitpass/common/error/SuccessCode.java, src/main/java/org/example/fitpass/domain/gym/controller/GymController.java, src/main/java/org/example/fitpass/domain/gym/dto/response/GymResponseDto.java, src/main/java/org/example/fitpass/domain/gym/service/GymService.java
- refactor/gym-url,dto -> dev
- url 부분 gym,image -> gyms,images로 수정
- response 부분에 gymId 추가
- 관련 이슈 번호: #87 
- x
=> refactor:url 및 dto response 수정

src/main/java/org/example/fitpass/common/error/ExceptionCode.java, src/main/java/org/example/fitpass/common/response/ResponseMessage.java, src/main/java/org/example/fitpass/domain/fitnessGoal/controller/DailyRecordController.java, src/main/java/org/example/fitpass/domain/fitnessGoal/controller/FitnessGoalController.java, src/main/java/org/example/fitpass/domain/fitnessGoal/controller/WeightRecordController.java, src/main/java/org/example/fitpass/domain/fitnessGoal/dto/request/DailyRecordCreateRequestDto.java, src/main/java/org/example/fitpass/domain/fitnessGoal/dto/request/WeightRecordCreateRequestDto.java, src/main/java/org/example/fitpass/domain/fitnessGoal/entity/WeightRecord.java, src/main/java/org/example/fitpass/domain/fitnessGoal/repository/FitnessGoalRepository.java, src/main/java/org/example/fitpass/domain/fitnessGoal/service/DailyRecordService.java, src/main/java/org/example/fitpass/domain/fitnessGoal/service/FitnessGoalService.java, src/main/java/org/example/fitpass/domain/fitnessGoal/service/WeightRecordService.java, src/main/java/org/example/fitpass/domain/point/controller/AdminPointController.java, src/main/java/org/example/fitpass/domain/point/controller/PointController.java, src/main/java/org/example/fitpass/domain/point/dto/response/PointBalanceResponseDto.java, src/main/java/org/example/fitpass/domain/point/service/PointService.java, src/main/java/org/example/fitpass/domain/reservation/service/ReservationService.java, src/main/java/org/example/fitpass/domain/user/Gender.java, src/test/java/org/example/fitpass/ReservationConcurrencyTest.java
- refactor/reservation, point, exception, user -> dev
- refatoring : point 객체 형태로 반환, FitnessGoal URL api 변경, USER의 Role 오타 수정
- 관련 이슈 번호: close #108 
=> [#108]refatoring : point 객체 형태로 반환, FitnessGoal URL api 변경, USER의 Role 오타 수정

src/main/java/org/example/fitpass/common/error/SuccessCode.java, src/main/java/org/example/fitpass/domain/gym/controller/GymController.java, src/main/java/org/example/fitpass/domain/gym/dto/response/GymDetailResponDto.java, src/main/java/org/example/fitpass/domain/gym/service/GymService.java, src/main/java/org/example/fitpass/domain/review/dto/response/GymRatingResponseDto.java, src/main/java/org/example/fitpass/domain/review/dto/response/TrainerRatingResponseDto.java, src/main/java/org/example/fitpass/domain/review/entity/Review.java, src/main/java/org/example/fitpass/domain/review/repository/ReviewRepository.java
- feature/review2 -> dev
- 평점 조회 기능 추가
- 관련 이슈 번호: close #110 
=> [#110] feat : 평점 조회 기능 추가

src/main/java/org/example/fitpass/common/error/ExceptionCode.java, src/main/java/org/example/fitpass/common/error/SuccessCode.java, src/main/java/org/example/fitpass/domain/reservation/controller/ReservationController.java, src/main/java/org/example/fitpass/domain/reservation/dto/request/ReservationRequestDto.java, src/main/java/org/example/fitpass/domain/reservation/entity/Reservation.java, src/main/java/org/example/fitpass/domain/reservation/repository/ReservationRepository.java, src/main/java/org/example/fitpass/domain/reservation/scheduler/ReservationScheduler.java, src/main/java/org/example/fitpass/domain/reservation/service/ReservationService.java
- Feature/reservation6
- 예약 로직 알림 기능 추가, 예약 스케줄러로 관리, 예약 승인/거절 API로 추가
- 관련 이슈 번호: close #124 
=> [#124] Feature/reservation6 예약 로직 알림 기능 추가, 예약 스케줄러로 관리, 예약 승인/거절 API로 추가

src/main/java/org/example/fitpass/config/NotificationConfig.java, src/main/java/org/example/fitpass/config/RedisConfig.java, src/main/java/org/example/fitpass/config/RedisDao.java, src/main/java/org/example/fitpass/config/RedisService.java
- ex) feature/reservation6 -> dev
- Redis 빈 등록
- 관련 이슈 번호: close #132
=> [#132] feat : RedisConfig 빈 등록

src/main/java/org/example/fitpass/common/error/SuccessCode.java, src/main/java/org/example/fitpass/domain/membership/repository/MembershipPurchaseRepository.java, src/main/java/org/example/fitpass/domain/trainer/entity/Trainer.java, src/test/java/org/example/fitpass/chat/controller/ChatControllerIntegrationTest.java, src/test/java/org/example/fitpass/chat/controller/ChatControllerTest.java, src/test/java/org/example/fitpass/chat/controller/StompChatControllerTest.java, src/test/java/org/example/fitpass/chat/integration/ChatIntegrationTest.java, src/test/java/org/example/fitpass/chat/scenario/ChatScenarioTest.java, src/test/java/org/example/fitpass/chat/service/ChatServiceTest.java, src/test/java/org/example/fitpass/membership/controller/MembershipControllerIntegrationTest.java, src/test/java/org/example/fitpass/membership/controller/MembershipControllerTest.java, src/test/java/org/example/fitpass/membership/controller/MembershipPurchaseControllerIntegrationTest.java, src/test/java/org/example/fitpass/membership/controller/MembershipPurchaseControllerTest.java, src/test/java/org/example/fitpass/membership/scenario/MembershipScenarioTest.java, src/test/java/org/example/fitpass/membership/service/MembershipPurchaseServiceIntegrationTest.java, src/test/java/org/example/fitpass/membership/service/MembershipPurchaseServiceTest.java, src/test/java/org/example/fitpass/membership/service/MembershipServiceIntegrationTest.java, src/test/java/org/example/fitpass/membership/service/MembershipServiceScenarioTest.java, src/test/java/org/example/fitpass/membership/service/MembershipServiceTest.java, src/test/java/org/example/fitpass/payment/PaymentScenarioTest.java, src/test/java/org/example/fitpass/reservation/ReservationServiceTest.java, src/test/java/org/example/fitpass/trainer/TrainerServiceTest.java
- ex) feat/chat test code -> dev
-  Chat, MemeberShip TestCode 추가
- 관련 이슈 번호:  close#162 
=> [#162] Chat, MemeberShip TestCode 추가

src/test/java/org/example/fitpass/chat/controller/ChatControllerIntegrationTest.java, src/test/java/org/example/fitpass/chat/controller/ChatControllerTest.java, src/test/java/org/example/fitpass/chat/service/ChatServiceTest.java, src/test/java/org/example/fitpass/payment/PaymentIntegrationTest.java, src/test/java/org/example/fitpass/reservation/ReservationServiceTest.java
- ex) feat/chatTestCode -> dev
- "ChatTest부분 수정  "
- 관련 이슈 번호:  close#170
=> [#170]fix : "ChatTest부분 수정  "

src/main/java/org/example/fitpass/domain/auth/controller/AuthController.java
- Feature/code convention  -> dev
- Readme, 스웨거 오타 수정
- 관련 이슈 번호: close #174 
=> [#174]Feature/code convention Readme, 스웨거 오타 수정
